baseURL = "https://makyo.ink/"
languageCode = "en-us"
title = "The Writing of Madison Rye Progress"

[taxonomies]
  tag = "tags"
  category = "categories"
  rating = "ratings"
  series = "series"

[permalinks]
  post = "/:filename/"

[markup.goldmark.renderer]
  unsafe= true
